:docinfo:
include::./common_docinfo_vars.adoc[]
include::./gs_rancher-rke2-nvidia-gpu-operator-vars.adoc[]
[#art-{article-id}]

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// GENERAL COMMENTS
//   - See the SUSE TRD Contributors Guide for detailed guidance:
//     https://documentation.suse.com/trd/contributors/single-html/suse-trd_contrib-guide/
//   - Keep in mind that this is a "getting started" guide.
//   - Write to the audience you are trying to reach.
//   - Add or remove sections and subsections as needed.
// 
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// DOCUMENT ATTRIBUTES AND VARIABLES
//
// NOTES:
// 1. Define and use document attributes or variables in the vars file.
// 2. Update the docinfo.xml file as needed.
//
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


= {title}: {subtitle}



== Introduction

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Provide a motivation for the document in 2-4 sentences to identify:
//   - what the document is about
//   - why it may be of interest to the reader
//   - what products are being highlighted
// Include an approved SUSE | Partner logo lock-up if possible
// Include any additional, relevant details
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

Graphics Processing Units (GPUs) provide unique capabilities for accelerating a broad spectrum of workloads, such as artificial intelligence and machine learning, scientific and engineering simulations, and many more.
Developing and deploying these workloads in containers on Kubernetes clusters offers potential for improved portability, scale, and efficiency.
However, GPU resources are not automatically visible or accessible to workloads running in containers.

In this guide, you learn how to:

* install the {nvidia-drv} on each worker node of the {rke2-full} cluster

* use a {helm-org} chart to deploy the {nvidia-op} to the {rke2-full} cluster


=== Scope

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Specify what this guide covers in no more than 2 sentences.
//   E.g., "You will learn how to ..."
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


This guide covers the following:

* finding and installing the appropriate {nvidia-drv} for the {nvidia-org} GPU installed on the {rke2} cluster

* finding and deploying the appropriate version of the {nvidia-op}

* verifying the functionality of the {nvidia-op} and the {nvidia-drv}


=== Audience

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Identify for whom this document is intended, perhaps with:
//   - topics of interests (e.g., machine learning, security, etc.)
//   - job roles (e.g., developer, administrator, platform architect, etc.)
//   - required skills
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


This guide is intended for high technology professionals (including Kubernetes administrators, proficient DevOps practitioners, and application developers) seeking to unlock the full potential of their GPU-accelerated containerized applications.

To be successful, you need a foundational understanding of Linux, Kubernetes, and {nvidia-org} GPU technologies.



=== Acknowledgements

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Acknowledge contributors not listed as authors.
// Something like:
//   The authors wish to acknowledge the contributions of the following
//   individuals:
//   * {contrib1-firstname} {contrib1-surname}, {contrib1-jobtitle}, {contrib1-orgname}
//   * {contrib2-firstname} {contrib2-surname}, {contrib2-jobtitle}, {contrib2-orgname}
// NOTE: If there are none, comment out this section.
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

The author wants to acknowledge contributions to this guide by:

* {contrib2-firstname} {contrib2-surname}, {contrib2-orgname}, {contrib2-jobtitle}
* {editor1-firstname} {editor1-surname}, {editor1-orgname}, {editor1-jobtitle}



== Prerequisites

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Identify minimum requirements (prerequisites) the reader
// would need in order to follow the steps of this guide.
// - Use an unordered list.
// - Use proper product names.
// - Identify product versions.
// - Link to existing resources whenever possible.
// - Keep this section brief but elaborate as needed.
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


Before you embark on the procedures outlined in this guide, ensure that your environment is ready with the resources listed here.

. {sles-full}
//
+
{sles-full} is the open, secure, and compliant enterprise Linux operating system to future-proof business-critical workloads.
//
+
This guide was validated with *{sles-full} {sles-version} SP{sles-sp}* as the operating system of the Kubernetes worker nodes.
//
+
You will need to install a few tools to help with installation of the {nvidia-drv}.
+
[NOTE]
====
Running certain commands requires root privileges.
However, for security reasons and to avoid mistakes, it is not recommended to log in as root.
A safer approach is to log in as a regular user, and then use `sudo` to run commands with elevated privileges.
See https://documentation.suse.com/sles/15-SP6/single-html/SLES-administration/#cha-adm-sudo[sudo basics] in the SUSE Linux Enterprise Server Administration Guide.
====

.. To install the {nvidia-drv}, first install `pciutils` and `wget`.
//
+
[source, console]
----
sudo zypper install pciutils wget 
----

.. Enable the Desktop Applications, Development Tools, and {nvidia-org} Compute {sles-docs-modules}[modules]:
+
[source, console, subs="attributes+"]
----
VER={sles-version}
SP={sles-sp}
sudo SUSEConnect -p sle-module-desktop-applications/$\{VER\}.$\{SP\}/x86_64
sudo SUSEConnect -p sle-module-development-tools/$\{VER\}.$\{SP\}/x86_64
sudo SUSEConnect -p sle-module-NVIDIA-compute/$\{VER\}/x86_64
----


. {rke2-full} ({rke2})
//
+
{rke2-docs}[{rke2}] is the security focused Kubernetes distribution developed by SUSE.
+
Ensure your worker nodes are part of an {rke2} cluster.
You can {rke2-docs}install/quickstart[deploy] {rke2} on worker nodes manually or use {rancher-docs-rke2}[Rancher by SUSE] to create and configure the cluster.
+
.  {rancher-full}
//
+
Your {rke2} cluster should be under the management of {rancher-full} to allow for installing and maintaining the {nvidia-org} software.
//
+
{rancher} provides a shell interface through the management web interface that includes tools like kubectl and {helm-org}. 
This comes in the form of a non-persistent container running on the {rancher} Kubernetes cluster.
This approach provides numerous security advantages. 
Users must first authenticate through {rancher-full} before they can view or manage downstream clusters. 
This is more secure than providing users with kubeconfig files that don't require authentication and could get checked into a version control system or otherwise end up in the wrong hands.
In addition, any sensitive data saved in the shell session will be deleted when the container exits.
//
+
* {rke2-full} cluster
//
+
Your {rke2} Kubernetes cluster must have worker nodes that are equipped and configured with {nvidia-dc-url}[Data Center class {nvidia-org} GPUs].


== Install the {nvidia-drv} on each GPU equipped worker node

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Detail the steps of the installation procedure.
// Replace 'Procedure' with one or more appropriate sections, such as:
// - 'Setting up the environment'
// - 'Installing the components'
// - 'Configuring and tuning'
// - 'Validating the deployment'
// You may find it useful to organize complex procedures into
// subsections.
//
// - As appropriate, make use of:
//   - Ordered lists for steps
//   - Code blocks for source code and console commands
//     Readers should be able to use copy and paste to leverage
//     commands and code in their environments
//   - Listing blocks for output
//   - Screenshots and diagrams
//   - Admonitions (notes, tips, warnings, etc.)
//
// NOTE: Always include some validation or verification in your guide.
//
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

. On each GPU configured worker node, deterimine which GPU(s) are installed:
//
+
[source, console, subs="attributes+"]
----
sudo lspci -v | grep -i nvidia
----
//
+
. Remove all {nvidia-org} packages that have been previously installed:
//
+
[source, console, subs="attributes+"]
----
sudo zypper remove *nvidia*
----
//
+

. Find the latest "Data Center / Tesla" driver for "Linux x64 SLES 15" using "Any CUDA Toolkit Version" for the GPU(s) installed on your worker nodes at {nvidia-drv-url}[{nvidia-org} Driver Downloads].
+
[NOTE]
====
You can move the driver package to each of the GPU worker nodes in whatever way you wish. One way to do this is described below, but it certainly isn't the only way.
====
+
.. Click on the "Find" button.
+
.. Click on the "View" button to see the details for the driver. 
+
.. Right click on the "Download" button, and select "Copy Link".
+ 
.. In a terminal window on each GPU worker nodes, download the package with the `wget` command. For example:
+
[source, console, subs="attributes+"]
----
wget https://us.download.nvidia.com/tesla/560.35.03/nvidia-driver-local-repo-sles15-560.35.03-1.0-1.x86_64.rpm
----
//
+
. Install the driver package with the `sudo rpm -i` command. For example:
+
[source, console, subs="attributes+"]
----
sudo zypper install ./nvidia-driver-local-repo-sles15-560.35.03-1.0-1.x86_64.rpm
----
//
+
. Install the CUDA drivers:
+
[source, console, subs="attributes+"]
----
sudo zypper install cuda-drivers
----
+
. Reboot each GPU equipped worker node, one at a time:
+
[source, console, subs="attributes+"]
----
sudo reboot
----
+
. After each worker node has successfully rebooted, ensure the {nvidia-org} kernel modules have been loaded:
+
[source, console]
----
sudo lsmod | grep nvidia
----
+
You should see the `nvidia`, `nvidia_drm`, `nvidia_modeset`, and `nvidia_uvm` kernel modules have been loaded.

. Verify the `nvidia-smi` utility can communicate with the GPU.
+
[source, console, subs="attributes+"]
----
sudo nvidia-smi
----

== Deploying the {nvidia-op} to an {rke2} cluster

The remainder of this process will be completed through the {rancher} UI. 
Leveraging the {rancher} UI is more secure than managing Kubernetes clusters from a workstation.
Working through the {rancher} UI ensures all administrative actions are performed through an authenticated session.
In addition, no sensitive data, such as a kubeconfig file, can fall into the wrong hands.

Kubernetes provides access to special hardware, such as GPUs, network adapters, and other devices through the {kubernetes-docs}concepts/extend-kubernetes/compute-storage-net/device-plugins/[device plugin framework].
Configuring and managing these resources involves multiple software components, including drivers, libraries, and container runtimes.
This can be difficult and prone to error.
The {nvidia-op} helps overcome these difficulties using the Kubernetes operator framework to automate management of {nvidia-org} software components.

The preferred method for installing the {nvidia-op} is with the {helm-docs}[Helm] Kubernetes package manager.
Using {rancher-full} to manage your {rke2} cluster allows you to more easily manage the cluster, including using Kubectl and {helm-org} without having to download the kubeconfig file for the cluster or install extra software on an external workstation.
In addition, managing Kubernetes clusters exclusively through {rancher} ensure all administrative actions are allowed only after proper user authentication, rather than allowing unauthenticated access to anyone possessing a kubeconfig file.

. Log in to your {rancher} server.
+
. Select your cluster, then click the `Explore` button (if shown).
+
. Click the {rancher-kubectl-shell} icon at the top right of the window.
+
. When the {rancher-kubectl-shell} is ready, add the {nvidia-org} helm software repository:
+
[source, console, subs="attributes+"]
----
helm repo add nvidia {nvidia-helm-url}
helm repo update
----
+
. Set this variable for the most current version of the {helm-org} chart:
+
[source, console]
----
export OPERATOR_VERSION=$(helm search repo nvidia/gpu-operator | grep 'gpu' | cut -f 2) && echo ${OPERATOR_VERSION}
----
+
. Deploy the {nvidia-op} with {helm-org}:
+
[source, console]
----
helm install -n gpu-operator \ 
  --generate-name \ 
  --wait \ 
  --create-namespace \ 
  --version=${OPERATOR_VERSION} \ 
  nvidia/gpu-operator \ 
  --set operator.defaultRuntime=containerd \ 
  --set toolkit.env[0].name=CONTAINERD_CONFIG \ 
  --set toolkit.env[0].value=/var/lib/rancher/rke2/agent/etc/containerd/config.toml \ 
  --set toolkit.env[1].name=CONTAINERD_SOCKET \ 
  --set toolkit.env[1].value=/run/k3s/containerd/containerd.sock \ 
  --set toolkit.env[2].name=CONTAINERD_RUNTIME_CLASS \ 
  --set toolkit.env[2].value=nvidia \ 
  --set toolkit.env[3].name=CONTAINERD_SET_AS_DEFAULT \ 
  --set-string toolkit.env[3].value=true
----
+
. The {nvidia-op} {helm-org} chart has been successfully deployed when it shows the output:
+
[listing]
----
STATUS: deployed
REVISION: 1
TEST SUITE: None
----
+
. Verify the {nvidia-op}, {nvidia-drv}, and associated elements have been deployed correctly.
+
[source, console]
----
kubectl get pods -n gpu-operator
----
+
You should see output similar to the following:
+
[listing]
----
NAME                                                              READY   STATUS        RESTARTS   AGE
gpu-feature-discovery-vl88c                                       1/1     Running       0          1h
gpu-operator-1722528349-node-feature-discovery-prune-mskxx        0/1     Completed     0          1h
gpu-operator-1724973943-node-feature-discovery-gc-5f6ffbb6vbcw6   1/1     Running       0          1h
gpu-operator-1724973943-node-feature-discovery-master-64d4mwvdn   1/1     Running       0          1h
gpu-operator-1724973943-node-feature-discovery-worker-8st9m       1/1     Running       0          1h
gpu-operator-1724973943-node-feature-discovery-worker-rm9m7       1/1     Running       0          1h
gpu-operator-68b4f6cc9c-sc7bc                                     1/1     Running       0          1h
nvidia-container-toolkit-daemonset-f6xl8                          1/1     Running       0          1h
nvidia-cuda-validator-dc5l5                                       0/1     Completed     0          1h
nvidia-dcgm-exporter-z469h                                        1/1     Running       0          1h
nvidia-device-plugin-daemonset-5vcjt                              1/1     Running       0          1h
nvidia-mig-manager-89v9f                                          1/1     Running       0          1h
nvidia-operator-validator-ggk82                                   1/1     Running       0          1h
----


== Validating the state of software

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Illustrate functionality with a demonstration.
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

The {nvidia-op} {helm-org} chart provides two pods that validate the state of the installed software.

. Validate the state of the {nvidia-op} software.
+
[source, console]
----
kubectl logs -n gpu-operator -l app=nvidia-operator-validator -c nvidia-operator-validator
----
+
The output should be similar to:
+
[listing]
====
*all validations are successful*
====

. Validate the state of the {nvidia-cuda} software.
+
[source, console]
----
kubectl logs -n gpu-operator -l app=nvidia-cuda-validator -c nvidia-cuda-validator
----
+
The output should be similar to:
+
[listing]
====
*cuda workload validation is successful*
====

== Summary

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Summarize:
// - Solution description
// - Motivation for the guide
// - What was done
// - Suggested next steps for the learning journey
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

Graphics Processing Units (GPUs) have become an essential technology of the modern era, accelerating time to insight and expanding capabilities.
GPUs have had dramatic impacts in artificial intelligence, machine learning, scientific and engineering simulation, and other high-performance computing applications.
Equally dramatic have been the impacts of container technologies, reshaping how applications are developed, deployed, and managed.
Bringing these two technologies together offers many benefits, including faster development, improved application portability, easier scaling, and streamlined administration.

In this guide, you learned how to:

* find and install the appropriate {nvidia-drv} on GPU equipped worker nodes

* deploy the {nvidia-op} {helm-org} chart on {rke2-full} clusters


The strategic choice of {sles-full} as the foundation for this design underscores a commitment to security and supportability.
Organizations with exacting security requirements depend on the numerous certifications of {sles-full}, including Common Criteria, FIPS, and EAL.
This is enhanced with the choice of a security focused Kubernetes distribution, such as {rke2-full}.
With SUSE's commitment to providing robust support for heterogeneous software stacks, customers can design their IT landscapes to suit their unique challenges without compromising on security, capability, or performance.







// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Do not modify below this break.
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

++++
<?pdfpagebreak?>
++++


:leveloffset: 0

== Legal notice
include::common_trd_legal_notice.adoc[]

++++
<?pdfpagebreak?>
++++


:leveloffset: 0
include::common_gfdl1.2_i.adoc[]

//end
